(define (problem strips-gripper) 
(:domain strips-gripper) 
(:objects ROOM1 ROOM1 BALL1 BALL2 LEFT RIGHT )
(:init 	(ROOM ROOM1)
	(ROOM ROOM2)
	(BALL BALL1)
	(BALL BALL2)
	(GRIPPER LEFT)
	(GRIPPER RIGHT)
	(AT-ROBBY ROOM1)
	(FREE LEFT)
	(FREE RIGHT)
	(AT BALL1 ROOM1)
	(AT BALL2 ROOM1)
)
(:goal 	(AND (AT BALL1 ROOM2)
	(AT BALL2 ROOM2))
)
)