(define (problem strips-gripper4)
   (:domain gripper-strips)
   (:objects rooma roomb roomc ball1 ball2 ball3 ball4 left right)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (ball ball1)
          (ball ball2)
          (ball ball3)
          (ball ball4)
          (gripper left)
          (gripper right)
          (at-robby rooma)
          (free left)
          (free right)
          (at ball1 rooma)
          (at ball2 roomb)
          (at ball2 roomc)
          (at ball4 rooma)
          (= (dist-covered) 0 )
          (= (distance rooma roomb) 100)
          (= (distance roomb rooma) 100)
          (= (distance rooma roomc) 1)
          (= (distance roomc rooma) 1))
   (:goal (and (at ball1 rooma)
               (at ball2 rooma)))
    (:metric minimize (dist-covered))
)