(define (problem findGold-4)
    (:domain findGold)
    
    (:objects box1 key1 box2 key2 box3 key3 box4 key4 diamond)
    
    (:init (box box1)
        (box box2)
        (box box3)
        (box box4)
        (key key1)
        (key key2)
        (key key3)
        (key key4)
        (diamond diamond)
        (hand key1)
        (contains box1 key2)
        (contains box2 key3)
        (contains box3 key4)
        (contains box4 diamond)
        (opens box1 key1)
        (opens box2 key2)
        (opens box3 key3)
        (opens box4 key4)
        (locked box1)
        (locked box2)
        (locked box3)
        (locked box4))
        
    (:goal (hand diamond))
)